version: "3"

services:
  knn_sv:
    container_name: knn_sv
    image: 0eta0/har-knn-api:latest
    volumes:
      - ./db/:/knn/db/
    logging:
      driver: journald
  tools_nginx:
    container_name: tools_nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sites-config/:/etc/nginx/sites-config/:ro
    ports:
      - 8911:8911
    links:
      - knn_sv
    depends_on:
      - knn_sv
    logging:
      driver: journald